trainer:
  precision: bf16-mixed
  logger:
  - class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: /Users/Shinji/models  # TODO: fix for your environment.
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: /Users/Shinji/models  # TODO: fix for your environment.
  callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      min_delta: 0.0
      patience: 10
      verbose: true
      mode: min
  max_epochs: 100
  max_time: 00:06:00:00
  gradient_clip_val: 3
model:
  class_path: yoyodyne.models.SoftAttentionGRUModel
  init_args:
    source_encoder:
      class_path: yoyodyne.models.modules.GRUEncoder
      init_args:
        bidirectional: true
        dropout: ${model.init_args.decoder_dropout}
        embedding_size: ${model.init_args.embedding_size}
        hidden_size: ${model.init_args.decoder_hidden_size}
    decoder_hidden_size: 100
    decoder_dropout: 0.3
    embedding_size: 300
    optimizer:
      class_path: torch.optim.Adadelta
      init_args:
        lr: 1.0
data:
  model_dir: /Users/Shinji/models  # TODO: fix for your environment.
  train: /Users/Shinji/train.tsv  # TODO: fix for your environment.
  val: /Users/Shinji/dev.tsv  # TODO: fix for your environment.
  predict: /Users/Shinji/test.tsv  # TODO: fix for your environment.
  test: /Users/Shinji/test.tsv  # TODO: fix for your environment.
checkpoint:
  filename: model-{epoch:03d}-{val_accuracy:.4f}
  monitor: val_accuracy
  verbose: true
  mode: max
prediction:
  path: /Users/Shinji/predict.txt  # TODO: fix for your environment.
