precision: bf16-mixed
gradient_clip_val: 3
max_epochs: 100
max_time: 00:06:00:00
callbacks:
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      patience: 10
      verbose: true
logger:
  - class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: /Users/Shinji/models  # TODO: fix for your environment.
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: unit1
      save_dir: /Users/Shinji/models  # TODO: fix for your environment.
